create extension if not exists pgcrypto;

create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 display_name text, avatar_url text, timezone text default 'Asia/Tehran',
 locale text default 'fa-IR', created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.emotions (
 id bigint generated by default as identity primary key,
 name_fa text not null unique, slug text not null unique, category text not null,
 valence smallint not null check(valence between -5 and 5),
 arousal smallint not null check(arousal between 1 and 5),
 icon text, is_active boolean default true, sort_order integer default 0
);

create table if not exists public.mood_entries (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 recorded_at timestamptz not null default now(), note text,
 overall_valence numeric(5,2) not null default 0, overall_arousal numeric(5,2) not null default 0,
 mood_score numeric(6,2) not null default 0 check(mood_score between -100 and 100),
 created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.mood_entry_emotions (
 id uuid primary key default gen_random_uuid(), mood_entry_id uuid not null references public.mood_entries(id) on delete cascade,
 emotion_id bigint not null references public.emotions(id), intensity smallint not null check(intensity between 1 and 10),
 note text, unique(mood_entry_id,emotion_id)
);

create table if not exists public.journal_entries (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 title text, content text not null, entry_type text default 'daily', mood_entry_id uuid references public.mood_entries(id) on delete set null,
 is_favorite boolean default false, is_private boolean default true, locked_until timestamptz, occurred_at timestamptz default now(),
 created_at timestamptz default now(), updated_at timestamptz default now(), archived_at timestamptz, deleted_at timestamptz
);
create table if not exists public.journal_revisions (
 id uuid primary key default gen_random_uuid(), journal_entry_id uuid references public.journal_entries(id) on delete cascade,
 title text, content text not null, created_at timestamptz default now()
);

create table if not exists public.habits (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 title text not null, description text, frequency_type text not null default 'daily',
 target_count integer default 1, target_value numeric, unit text, preferred_time time,
 is_active boolean default true, paused_until date, created_at timestamptz default now(),
 updated_at timestamptz default now(), archived_at timestamptz
);
create table if not exists public.habit_schedules (
 id uuid primary key default gen_random_uuid(), habit_id uuid references public.habits(id) on delete cascade,
 weekday smallint check(weekday between 0 and 6), unique(habit_id,weekday)
);
create table if not exists public.habit_logs (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 habit_id uuid not null references public.habits(id) on delete cascade, log_date date not null default current_date,
 status text not null check(status in ('completed','partial','missed','skipped','forgotten')),
 value numeric, note text, created_at timestamptz default now(), unique(habit_id,log_date)
);

create table if not exists public.tasks (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 title text not null, description text, status text default 'planned',
 priority text default 'medium', due_at timestamptz, reminder_at timestamptz, next_action text,
 recurrence_rule text, project_name text, completed_at timestamptz, created_at timestamptz default now(),
 updated_at timestamptz default now(), archived_at timestamptz
);

create table if not exists public.wishes (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 title text not null, description text, why_it_matters text, desired_feeling text, first_step text,
 next_step text, obstacles text, horizon text, status text default 'active',
 progress smallint default 0 check(progress between 0 and 100), cover_image_path text,
 created_at timestamptz default now(), updated_at timestamptz default now(), achieved_at timestamptz, archived_at timestamptz
);
create table if not exists public.wish_entries (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 wish_id uuid references public.wishes(id) on delete cascade, title text, content text not null,
 created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.dreams (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 title text not null, summary text, cover_image_path text, status text default 'active',
 created_at timestamptz default now(), updated_at timestamptz default now(), archived_at timestamptz
);
create table if not exists public.dream_sections (
 id uuid primary key default gen_random_uuid(), dream_id uuid not null references public.dreams(id) on delete cascade,
 title text not null, content text not null default '', sort_order integer default 0,
 created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.prayer_lines (
 id bigint generated by default as identity primary key, text text not null unique,
 category text not null, period text default 'any', valence_min smallint default -5,
 valence_max smallint default 5, arousal_min smallint default 1, arousal_max smallint default 5,
 is_active boolean default true
);
create table if not exists public.prayer_views (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 prayer_line_id bigint references public.prayer_lines(id) on delete cascade, shown_on date default current_date,
 reaction text, is_favorite boolean default false, reflection text, unique(user_id,prayer_line_id,shown_on)
);

create table if not exists public.daily_reviews (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 review_date date not null default current_date, morning_intention text, most_important_task text,
 evening_reflection text, important_event text, learned_about_myself text, surrender_note text,
 gratitude text, created_at timestamptz default now(), updated_at timestamptz default now(),
 unique(user_id,review_date)
);

create index if not exists idx_mood_user_date on public.mood_entries(user_id,recorded_at desc);
create index if not exists idx_journal_user_date on public.journal_entries(user_id,created_at desc);
create index if not exists idx_tasks_user_due on public.tasks(user_id,due_at);
create index if not exists idx_habit_logs_date on public.habit_logs(user_id,log_date);

alter table public.profiles enable row level security;
alter table public.mood_entries enable row level security;
alter table public.mood_entry_emotions enable row level security;
alter table public.journal_entries enable row level security;
alter table public.journal_revisions enable row level security;
alter table public.habits enable row level security;
alter table public.habit_schedules enable row level security;
alter table public.habit_logs enable row level security;
alter table public.tasks enable row level security;
alter table public.wishes enable row level security;
alter table public.wish_entries enable row level security;
alter table public.dreams enable row level security;
alter table public.dream_sections enable row level security;
alter table public.prayer_views enable row level security;

create policy "profile own" on public.profiles for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy "mood own" on public.mood_entries for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "mood emotions own" on public.mood_entry_emotions for all to authenticated
 using(exists(select 1 from public.mood_entries m where m.id=mood_entry_id and m.user_id=auth.uid()))
 with check(exists(select 1 from public.mood_entries m where m.id=mood_entry_id and m.user_id=auth.uid()));
create policy "journal own" on public.journal_entries for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "journal revision own" on public.journal_revisions for all to authenticated
 using(exists(select 1 from public.journal_entries j where j.id=journal_entry_id and j.user_id=auth.uid()))
 with check(exists(select 1 from public.journal_entries j where j.id=journal_entry_id and j.user_id=auth.uid()));
create policy "habit own" on public.habits for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "habit schedule own" on public.habit_schedules for all to authenticated
 using(exists(select 1 from public.habits h where h.id=habit_id and h.user_id=auth.uid()))
 with check(exists(select 1 from public.habits h where h.id=habit_id and h.user_id=auth.uid()));
create policy "habit log own" on public.habit_logs for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "task own" on public.tasks for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "wish own" on public.wishes for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "wish entry own" on public.wish_entries for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "dream own" on public.dreams for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "dream section own" on public.dream_sections for all to authenticated
 using(exists(select 1 from public.dreams d where d.id=dream_id and d.user_id=auth.uid()))
 with check(exists(select 1 from public.dreams d where d.id=dream_id and d.user_id=auth.uid()));
create policy "prayer view own" on public.prayer_views for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

grant select on public.emotions to authenticated;
grant select on public.prayer_lines to authenticated;

create or replace function public.get_daily_prayer_lines(requested_count integer default 2)
returns setof public.prayer_lines
language sql stable security invoker
as $$
 select p.* from public.prayer_lines p
 where p.is_active
 order by md5(p.id::text || current_date::text || coalesce(auth.uid()::text,''))
 limit greatest(1,least(requested_count,3));
$$;
grant execute on function public.get_daily_prayer_lines(integer) to authenticated;
